# HomeKit Config
homekit:
  auto_start: False
  safe_mode: true
  filter:
    include_entities:
      - light.hall
      - light.livingroom_1
      - light.livingroom_2
      - light.window_livingroom
      - light.kitchen
      - light.bedroom
      - light.bathroom
      - light.gateway_light
      - media_player.dunehd
      - media_player.sony_htnt5
      - media_player.sony_bravia_tv
      - script.dunehd_fastforward
      - script.dunehd_play_pause
      - script.sony_htnt5_volume_mute
      - script.light_livingroom_bright
      - script.light_livingroom_movie
      - script.light_livingroom_night
      - switch.smart_plug_bedroom
      - input_boolean.dfi
      - input_boolean.ott_club
      - input_boolean.kinopub
      - input_boolean.youtube
  entity_config:
    media_player.sony_bravia_tv:
      name: Зал Телевизор
      feature_list:
        - feature: on_off
    media_player.dunehd:
      name: Зал Дюна
      feature_list:
        - feature: on_off
    media_player.sony_htnt5:
      name: Зал Саундбар
      feature_list:
        - feature: on_off
    switch.smart_plug_bedroom:
      name: Спальня Розетка
      type: outlet
    script.light_livingroom_bright:
      name: Сцена Ярко
    script.light_livingroom_movie:
      name: Сцена Кино
    script.light_livingroom_night:
      name: Сцена Ночь


# Автоматизация
automation:
  # Задержка запуска HomeKit
  - alias: start_homeKit
    initial_state: true
    trigger:
      - platform: homeassistant
        event: start
    action:
      - delay: 00:01
      - service: homekit.start
